name: app_release_center
description: "Desktop release automation center for Flutter projects."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  archive: ^4.0.9
  cloud_firestore: ^6.8.0
  cryptography: ^2.9.0
  file_picker: 8.3.7
  file_selector: ^1.1.0
  firebase_auth: ^6.5.7
  firebase_core: ^4.13.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  get: ^4.7.3
  googleapis: ^16.0.0
  http: ^1.5.0
  oauth2: ^2.0.5
  path: ^1.9.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  uuid: ^4.6.0
  xml: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.20

flutter:
  uses-material-design: true
