name: app_management_center
description: "Desktop project management and release automation center for Flutter projects."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  archive: ^4.0.9
  cryptography: ^2.9.0
  desktop_drop: ^0.8.4
  desktop_webview_window: ^0.3.0
  enough_mail: ^2.1.7
  file_picker: 8.3.7
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  get: ^4.7.3
  googleapis: ^16.0.0
  http: ^1.5.0
  local_auth: ^3.0.2
  oauth2: ^2.0.5
  path: ^1.9.1
  path_provider: ^2.1.5
  pointycastle: ^4.0.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.5
  sqflite_common_ffi: ^2.4.3
  url_launcher: ^6.3.2
  uuid: ^4.6.0
  webview_windows: ^0.4.0
  xml: ^6.6.1
  yaml: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.20

flutter:
  uses-material-design: true
